export const REGISTER_USER_REQUEST: 'REGISTER/USER/REQUEST' = 'REGISTER/USER/REQUEST';
export const REGISTER_USER_SUCCESS: 'REGISTER/USER/SUCCESS' = 'REGISTER/USER/SUCCESS';
export const REGISTER_USER_FAILED: 'REGISTER/USER/FAILED' = 'REGISTER/USER/FAILED';

export const LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST' = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS: 'LOGIN_USER__SUCCESS' = 'LOGIN_USER__SUCCESS';
export const LOGIN_USER_FAILED: 'LOGIN_USER_FAILED' = 'LOGIN_USER_FAILED';

export const UPDATE_USER_DATA_REQUEST: 'UPDATE/USER/DATA/REQUEST' = 'UPDATE/USER/DATA/REQUEST';
export const UPDATE_USER_DATA_FAILED: 'UPDATE/USER/DATA/FAILED' = 'UPDATE/USER/DATA/FAILED';
export const UPDATE_USER_DATA_SUCCESS: 'UPDATE/USER/DATA/SUCCESS' = 'UPDATE/USER/DATA/SUCCESS';
export const UPDATE_USER_DATA_RESET: 'UPDATE/USER/DATA/RESET' = 'UPDATE/USER/DATA/RESET';

export const RESET_PASSWORD_REQUEST: 'RESET/PASSWORD/REQUEST' = 'RESET/PASSWORD/REQUEST';
export const RESET_PASSWORD_SUCCESS: 'RESET/PASSWORD/SUCCESS' = 'RESET/PASSWORD/SUCCESS';
export const RESET_PASSWORD_FAILED: 'RESET/PASSWORD/FAILED' = 'RESET/PASSWORD/FAILED';

export const GET_NEW_PASSWORD_REQUEST: 'GET_NEW/PASSWORD/REQUEST' = 'GET_NEW/PASSWORD/REQUEST';
export const GET_NEW_PASSWORD_SUCCESS: 'GET_NEW/PASSWORD/SUCCESS' = 'GET_NEW/PASSWORD/SUCCESS';
export const GET_NEW_PASSWORD_FAILED: 'GET/NEW/PASSWORD/FAILED' = 'GET/NEW/PASSWORD/FAILED';

export const REFRESH_TOKEN_REQUEST: 'REFRESH/TOKEN/REQUEST' = 'REFRESH/TOKEN/REQUEST';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH/TOKEN/SUCCESS' = 'REFRESH/TOKEN/SUCCESS';
export const REFRESH_TOKEN_FAILED: 'REFRESH/TOKEN/FAILED' = 'REFRESH/TOKEN/FAILED';

export const USER_LOGOUT: 'USER_LOGOUT' = 'USER_LOGOUT';