
export const CONSTRUCTOR_ADD: 'CONSTRUCTOR/ADD' = 'CONSTRUCTOR/ADD';
export const CONSTRUCTOR_DELETE: 'CONSTRUCTOR/DELETE' = 'CONSTRUCTOR/DELETE';
export const CONSTRUCTOR_REORDER: 'CONSTRUCTOR/REORDER' = 'CONSTRUCTOR/REORDER';
export const CONSTRUCTOR_RESET: 'CONSTRUCTOR/RESET' = 'CONSTRUCTOR/RESET';
