export const GET_ITEMS_REQUEST: 'GET/ITEMS_REQUEST' = 'GET/ITEMS_REQUEST';
export const GET_ITEMS_FAILED: 'GET/ITEMS_FAILED' = 'GET/ITEMS_FAILED';
export const GET_ITEMS_SUCCESS: 'GET/ITEMS_SUCCESS' = 'GET/ITEMS_SUCCESS';