export const ORDER_REQUEST: 'ORDER/REQUEST' = 'ORDER/REQUEST';
export const ORDER_SUCCESS: 'ORDER/SUCCESS' = 'ORDER/SUCCESS';
export const ORDER_FAILED: 'ORDER/FAILED' = 'ORDER/FAILED';
export const ORDER_RESET: 'ORDER/RESET' = 'ORDER/RESET';