export const ORDER_NUMBER_REQUEST: 'ORDER_NUMBER_REQUEST' = 'ORDER_NUMBER_REQUEST';
export const ORDER_NUMBER_SUCCESS: 'ORDER_NUMBER_SUCCESS' = 'ORDER_NUMBER_SUCCESS';
export const ORDER_NUMBER_FAILED: 'ORDER_NUMBER_FAILED' = 'ORDER_NUMBER_FAILED';